//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Controllers/PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController"",
    ""maps"": [
        {
            ""name"": ""KeyboardControls"",
            ""id"": ""1bb0efaf-2d4c-4406-acc7-460ef051732e"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4567b87a-810d-42fa-89a7-e5545bde1f2c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""75132f7f-4691-4e47-8fbb-81fe9d0b630a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopJump"",
                    ""type"": ""Button"",
                    ""id"": ""92d7d5ed-c0ac-4e71-859c-91eb0546f23c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""921bb3c4-6063-48ec-b2c1-d98c3862a0ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stand"",
                    ""type"": ""Button"",
                    ""id"": ""4f284f2b-0188-4e9c-acda-dc2f799d9fa3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""8136262c-11a9-4190-bb7c-679fac4554ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DrawSword"",
                    ""type"": ""Button"",
                    ""id"": ""8500b248-f157-4eb1-aaf8-1cf79505c91c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DrawShield"",
                    ""type"": ""Button"",
                    ""id"": ""fbad88d6-7ae4-4298-9190-ad947e31340b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""09751449-d3ff-491d-b38a-eda9f54e9a05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopBlock"",
                    ""type"": ""Button"",
                    ""id"": ""3ebdaf0f-4406-4d6d-94a2-7f4b1dca2e96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Moonwalk"",
                    ""type"": ""Button"",
                    ""id"": ""05f92b56-d5ec-4bbd-8c9a-0920cf9d6759"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop Moonwalk"",
                    ""type"": ""Button"",
                    ""id"": ""58cddff2-d8a5-4e73-b14c-6d6db1fd28ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enable Look"",
                    ""type"": ""Button"",
                    ""id"": ""96060355-bd00-4a9e-b2a3-ecb5bab43839"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop Look"",
                    ""type"": ""Button"",
                    ""id"": ""1a7bb388-985d-4282-bb7d-4947bcb12cc9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""df37ce2a-4773-48b3-8e3b-c170c0d6b9de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""AD"",
                    ""id"": ""7c9b8a0d-2cd5-4ee8-80ca-4926d1fa30f3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1fa7c5cf-a069-4524-ae5e-9638e58c7842"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ec04f458-16a8-42db-8d59-371a2f6973a5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""edb44b34-5ad9-41e2-a3d9-7cca30e0abc8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca137e47-81c1-4871-b491-4db91d60e00f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87781156-77b2-4420-be46-528699dca63c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dc8df44-a170-49c3-b21f-18ec1358e3b1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2aeb0eca-9f06-4a44-aea5-2c18cefceb65"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawSword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb5fe5ee-3c8f-48dd-ad2f-f2a9893ce686"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawShield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""644d82df-d594-4e3c-b778-8636e61e72d8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3683e896-1051-4780-b9bb-2ec5fc614375"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopBlock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ff43488-bb10-48ba-94c5-c6bccf91baae"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moonwalk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b72d3ef8-7e8c-4b4e-8828-aaf1fbbe41e4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop Moonwalk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f413f535-f975-43fc-9948-909d82815f62"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3fa4425-49fc-4a40-9fe1-6c4507bafef8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enable Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c330178-d9ab-4f17-8945-ef4472603fb7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3576ceb0-fbc3-4172-9028-0efe4626ccec"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // KeyboardControls
        m_KeyboardControls = asset.FindActionMap("KeyboardControls", throwIfNotFound: true);
        m_KeyboardControls_Movement = m_KeyboardControls.FindAction("Movement", throwIfNotFound: true);
        m_KeyboardControls_Jump = m_KeyboardControls.FindAction("Jump", throwIfNotFound: true);
        m_KeyboardControls_StopJump = m_KeyboardControls.FindAction("StopJump", throwIfNotFound: true);
        m_KeyboardControls_Crouch = m_KeyboardControls.FindAction("Crouch", throwIfNotFound: true);
        m_KeyboardControls_Stand = m_KeyboardControls.FindAction("Stand", throwIfNotFound: true);
        m_KeyboardControls_Attack = m_KeyboardControls.FindAction("Attack", throwIfNotFound: true);
        m_KeyboardControls_DrawSword = m_KeyboardControls.FindAction("DrawSword", throwIfNotFound: true);
        m_KeyboardControls_DrawShield = m_KeyboardControls.FindAction("DrawShield", throwIfNotFound: true);
        m_KeyboardControls_Block = m_KeyboardControls.FindAction("Block", throwIfNotFound: true);
        m_KeyboardControls_StopBlock = m_KeyboardControls.FindAction("StopBlock", throwIfNotFound: true);
        m_KeyboardControls_Moonwalk = m_KeyboardControls.FindAction("Moonwalk", throwIfNotFound: true);
        m_KeyboardControls_StopMoonwalk = m_KeyboardControls.FindAction("Stop Moonwalk", throwIfNotFound: true);
        m_KeyboardControls_EnableLook = m_KeyboardControls.FindAction("Enable Look", throwIfNotFound: true);
        m_KeyboardControls_StopLook = m_KeyboardControls.FindAction("Stop Look", throwIfNotFound: true);
        m_KeyboardControls_Pause = m_KeyboardControls.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyboardControls
    private readonly InputActionMap m_KeyboardControls;
    private IKeyboardControlsActions m_KeyboardControlsActionsCallbackInterface;
    private readonly InputAction m_KeyboardControls_Movement;
    private readonly InputAction m_KeyboardControls_Jump;
    private readonly InputAction m_KeyboardControls_StopJump;
    private readonly InputAction m_KeyboardControls_Crouch;
    private readonly InputAction m_KeyboardControls_Stand;
    private readonly InputAction m_KeyboardControls_Attack;
    private readonly InputAction m_KeyboardControls_DrawSword;
    private readonly InputAction m_KeyboardControls_DrawShield;
    private readonly InputAction m_KeyboardControls_Block;
    private readonly InputAction m_KeyboardControls_StopBlock;
    private readonly InputAction m_KeyboardControls_Moonwalk;
    private readonly InputAction m_KeyboardControls_StopMoonwalk;
    private readonly InputAction m_KeyboardControls_EnableLook;
    private readonly InputAction m_KeyboardControls_StopLook;
    private readonly InputAction m_KeyboardControls_Pause;
    public struct KeyboardControlsActions
    {
        private @PlayerController m_Wrapper;
        public KeyboardControlsActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_KeyboardControls_Movement;
        public InputAction @Jump => m_Wrapper.m_KeyboardControls_Jump;
        public InputAction @StopJump => m_Wrapper.m_KeyboardControls_StopJump;
        public InputAction @Crouch => m_Wrapper.m_KeyboardControls_Crouch;
        public InputAction @Stand => m_Wrapper.m_KeyboardControls_Stand;
        public InputAction @Attack => m_Wrapper.m_KeyboardControls_Attack;
        public InputAction @DrawSword => m_Wrapper.m_KeyboardControls_DrawSword;
        public InputAction @DrawShield => m_Wrapper.m_KeyboardControls_DrawShield;
        public InputAction @Block => m_Wrapper.m_KeyboardControls_Block;
        public InputAction @StopBlock => m_Wrapper.m_KeyboardControls_StopBlock;
        public InputAction @Moonwalk => m_Wrapper.m_KeyboardControls_Moonwalk;
        public InputAction @StopMoonwalk => m_Wrapper.m_KeyboardControls_StopMoonwalk;
        public InputAction @EnableLook => m_Wrapper.m_KeyboardControls_EnableLook;
        public InputAction @StopLook => m_Wrapper.m_KeyboardControls_StopLook;
        public InputAction @Pause => m_Wrapper.m_KeyboardControls_Pause;
        public InputActionMap Get() { return m_Wrapper.m_KeyboardControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardControlsActions set) { return set.Get(); }
        public void SetCallbacks(IKeyboardControlsActions instance)
        {
            if (m_Wrapper.m_KeyboardControlsActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnJump;
                @StopJump.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopJump;
                @StopJump.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopJump;
                @StopJump.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopJump;
                @Crouch.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnCrouch;
                @Stand.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStand;
                @Stand.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStand;
                @Stand.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStand;
                @Attack.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnAttack;
                @DrawSword.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnDrawSword;
                @DrawSword.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnDrawSword;
                @DrawSword.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnDrawSword;
                @DrawShield.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnDrawShield;
                @DrawShield.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnDrawShield;
                @DrawShield.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnDrawShield;
                @Block.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnBlock;
                @StopBlock.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopBlock;
                @StopBlock.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopBlock;
                @StopBlock.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopBlock;
                @Moonwalk.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnMoonwalk;
                @Moonwalk.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnMoonwalk;
                @Moonwalk.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnMoonwalk;
                @StopMoonwalk.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopMoonwalk;
                @StopMoonwalk.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopMoonwalk;
                @StopMoonwalk.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopMoonwalk;
                @EnableLook.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnEnableLook;
                @EnableLook.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnEnableLook;
                @EnableLook.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnEnableLook;
                @StopLook.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopLook;
                @StopLook.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopLook;
                @StopLook.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnStopLook;
                @Pause.started -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_KeyboardControlsActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_KeyboardControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @StopJump.started += instance.OnStopJump;
                @StopJump.performed += instance.OnStopJump;
                @StopJump.canceled += instance.OnStopJump;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Stand.started += instance.OnStand;
                @Stand.performed += instance.OnStand;
                @Stand.canceled += instance.OnStand;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @DrawSword.started += instance.OnDrawSword;
                @DrawSword.performed += instance.OnDrawSword;
                @DrawSword.canceled += instance.OnDrawSword;
                @DrawShield.started += instance.OnDrawShield;
                @DrawShield.performed += instance.OnDrawShield;
                @DrawShield.canceled += instance.OnDrawShield;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
                @StopBlock.started += instance.OnStopBlock;
                @StopBlock.performed += instance.OnStopBlock;
                @StopBlock.canceled += instance.OnStopBlock;
                @Moonwalk.started += instance.OnMoonwalk;
                @Moonwalk.performed += instance.OnMoonwalk;
                @Moonwalk.canceled += instance.OnMoonwalk;
                @StopMoonwalk.started += instance.OnStopMoonwalk;
                @StopMoonwalk.performed += instance.OnStopMoonwalk;
                @StopMoonwalk.canceled += instance.OnStopMoonwalk;
                @EnableLook.started += instance.OnEnableLook;
                @EnableLook.performed += instance.OnEnableLook;
                @EnableLook.canceled += instance.OnEnableLook;
                @StopLook.started += instance.OnStopLook;
                @StopLook.performed += instance.OnStopLook;
                @StopLook.canceled += instance.OnStopLook;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public KeyboardControlsActions @KeyboardControls => new KeyboardControlsActions(this);
    public interface IKeyboardControlsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnStopJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnStand(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnDrawSword(InputAction.CallbackContext context);
        void OnDrawShield(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnStopBlock(InputAction.CallbackContext context);
        void OnMoonwalk(InputAction.CallbackContext context);
        void OnStopMoonwalk(InputAction.CallbackContext context);
        void OnEnableLook(InputAction.CallbackContext context);
        void OnStopLook(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
